version: '3.0'

services:

    symfony:
      image: trosiki/trosiki:symfony5
      container_name: symfony
      volumes:
        - "/home/trosiki/Documentos/projects/www:/var/www"
        - "/home/trosiki/Documentos/projects/log:/var/log"
      restart: always
      ports:
        - 9000:9000
      links:
        - mysql:mysql

    nginx-symfony:
      image: trosiki/trosiki:nginx
      container_name: nginx_symfony
      volumes:
        - "/home/trosiki/Documentos/projects/www:/var/www"
        - "./common/default.conf:/etc/nginx/conf.d/default.conf"
        - "./common/default.conf:/etc/nginx/sites-available/default"
        - "./common/extra-conf.ini /usr/local/etc/php/conf.d/extra-conf.ini"
      ports:
        - 80:80
      depends_on:
        - symfony

    node:
      image: trosiki/trosiki:node
      container_name: node
      ports:
        - 4200:4200
      volumes:
        - "/home/trosiki/Documentos/projects/www/trosfolio_angular/:/home/node/app/"
      tty: true
      command:
        - /bin/sh
        - -c
        - |
           cd /home/node/app/frontend && npm start
      expose:
        - "4200"

    nginx_angular:
      image: trosiki/trosiki:nginx
      container_name: nginx_angular
      volumes:
        - "/home/trosiki/Documentos/projects/www/trosfolio_angular/angular8/:/var/www/html/"
      ports:
        - "81:80"

    mysql:
      image: mysql:8.0
      command: --default_authentication_plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: trosfoliodata
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - "/home/trosiki/Documentos/projects/mysql-data:/var/lib/mysql"