version: '3.0'

services:

    symfony:
      image: trosiki/trosiki:symfony5
      volumes:
        - ${WWW}:/var/www
        - ${LOGS}:/var/log
      restart: always
      ports:
        - 9000:9000
      links:
        - mysql:mysql

    nginx-symfony:
      image: trosiki/trosiki:nginx
      volumes:
        - ${WWW}:/var/www
        - ${DEFAULT_CONF_NGINX}:/etc/nginx/conf.d/default.conf
        - ${DEFAULT_CONF_NGINX}:/etc/nginx/sites-available/default
        - ${EXTRA_CONF_NGINX}:/usr/local/etc/php/conf.d/extra-conf.ini
      ports:
        - 80:80
      depends_on:
        - symfony

    node:
      image: trosiki/trosiki:node
      ports:
        - 4200:4200
      volumes:
        - "/home/trosiki/Documentos/projects/www/trosfolio_angular/:/home/node/app/"

    mysql:
      image: mysql:8.0
      command: --default_authentication_plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ${PATH_MYSQL_DATA}:/var/lib/mysql
      ports:
        - 3306:3306