version: '3.0'

services:
    symfony: 
      image: trosiki/trosiki:symfony5
      volumes:
        - "/home/trosiki/Documentos/projects/www:/var/www"
        - "/home/trosiki/Documentos/projects/log:/var/log"
      restart: always
      ports:
        - 80:80
      links:
        - mysql:mysql

    angular:
      image: node:current-alpine3.13
      restart: always

    mysql:
      image: mysql:8.0
      command: --default_authentication_plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: trosfoliodata
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - "/home/trosiki/Documentos/projects/mysql-data:/var/lib/mysql"